sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t aaaknot30/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aaaknot30/docker-react npm run test
